@url= http://localhost:3033


### show all users 
GET {{url}}/
content-type: application/json

### Add a user TEST
POST {{url}}/create
content-type: application/json

{
    "user": {
        "userName": "Test",
        "Hash": "eeenonso10",
        "email": "test@example.com"
    }
}