@url= http://localhost:3025


### show all users 
GET {{url}}/
content-type: application/json; 

### Add a user TEST
POST {{url}}/signup
content-type: application/json;

{
    "user": {
        "login": "Jacktest",
        "password": "1234"
 }
}